-- CREATE DATABASE ESTUDOS;
-- USE ESTUDOS;

-- CREATE TABLE ALUNOS (
-- CODIGO INT PRIMARY KEY,
-- NOME VARCHAR(50),
--    EMAIL VARCHAR(50),
-- TELEFONE VARCHAR(12)

-- INSERT INTO ALUNOS (CODIGO, NOME, EMAIL, TELEFONE) VALUES(1, 'PATRICIA ALVES', 'Pathy@gmail.com','69993119479')

-- INSERT INTO ALUNOS (CODIGO, NOME, EMAIL, TELEFONE) VALUES(2, 'MARCIO ', 'MARCIO@gmail.com','699932020055')

-- INSERT INTO ALUNOS (CODIGO, NOME, EMAIL, TELEFONE) VALUES(3, 'CARINTINA', 'CAREM@gmail.com','6565465588')

-- INSERT INTO ALUNOS (CODIGO, NOME, EMAIL, TELEFONE) VALUES(4, 'ANA BETARIZ', 'ANA@gmail.com','69993124578')

-- INSERT INTO ALUNOS (CODIGO, NOME, EMAIL, TELEFONE) VALUES(5, 'SOPHIA', 'SOSO@gmail.com','69993789546')

-- select * from alunos

-- select 1 / 8

-- CREATE TABLE FUNCIONARIOS (
--    CODIGO INT PRIMARY NOT NULL,
--    NOME VARCHAR(100) NOT NULL,
-- EMAIL VARCHAR(100) NOT NULL,
-- TELEFONE VARCHAR(12)NOT NULL,
  --  ENDERECO VARCHAR(150) NOT NULL,
   -- BAIRRO VARCHAR(150) NOT NULL,
   -- CIDADE VARCHAR(40) NOT NULL,
  -- ESTADO CHAR(2) NOT NULL,
   -- CARGO VARCHAR(40) NOT NULL,
   -- SALARIO DECIMAL(10,2) NOT NULL
    
    -- select * from funcionarios


	-- INSERT INTO FUNCIONARIOS Values(1,'ROZANA', 'ZANA@GMAIL.COM','699999188','RUA JIPA','DOMBOSCO','JIPARANA', 'RO', 'AUX','5.000')
    
   -- SELECT * FROM FUNCIONARIOS
    -- SELECT NOME, CARGO, SALARIO *1.20 FROM FUNCIONARIOS