USE DBSENAC;
CREATE TABLE CLIENTES (
	ID INT IDENTITY(1,1) NOT NULL,
	NOMECLIENTE VARCHAR(100) NOT NULL,
	ENDERECO VARCHAR(150) NOT NULL,
	BAIRRO VARCHAR(100) NOT NULL,
	CIDADE VARCHAR(100) NOT NULL,
	ESTADO VARCHAR(2) NOT NULL
);