USE [DBSENAC]
GO

INSERT INTO CLIENTES
(NOMECLIENTE,ENDERECO,BAIRRO,CIDADE,ESTADO)
     
VALUES
        ('MARCIO',
           'RUA RIO MAMORE',
           'DOM BOSCO',
           'JI-PARANA',
           'RO')
GO

SELECT * FROM CLIENTES
SELECT * FROM CLIENTES WHERE NOMECLIENTE  LIKE '%'+ 'P' + '%';
SELECT * FROM CLIENTES WHERE NOMECLIENTE  LIKE 'A%';
SELECT * FROM CLIENTES WHERE NOMECLIENTE  LIKE '%É';


