--USE  DBSENAC;
CREATE TABLE FUNCIONARIOS (
	COD INT IDENTITY(1,1),
	NOME VARCHAR(100),
	CARGO VARCHAR(100),
	SALARIO DECIMAL(10,2)
);

INSERT INTO FUNCIONARIOS (NOME, CARGO, SALARIO)
VALUES('WANDERLEY', 'PROGRAMADOR JR', 10000);
INSERT INTO FUNCIONARIOS (NOME, CARGO, SALARIO)
VALUES('PATRÍCIA', 'ANALISTA', 15000.59);
INSERT INTO FUNCIONARIOS (NOME, CARGO, SALARIO)
VALUES('CARITINA', 'GERENTE', 17000.99);
INSERT INTO FUNCIONARIOS (NOME, CARGO, SALARIO)
VALUES('MICHAEL', 'BADECO', 2000.32);
INSERT INTO FUNCIONARIOS (NOME, CARGO, SALARIO)
VALUES('CHAEL', '', 2000.32);


SELECT *FROM FUNCIONARIOS

SELECT AVG(SALARIO) FROM FUNCIONARIOS;
SELECT COUNT(NOME) FROM FUNCIONARIOS;
SELECT SUM(SALARIO) FROM FUNCIONARIOS;
SELECT COUNT(CARGO) FROM FUNCIONARIOS;

SELECT 1 + 5;

CREATE TABLE DEPENDENTES(
	COD INT,
	NOMEDEP VARCHAR(100),
);

INSERT INTO DEPENDENTES(COD, NOMEDEP)
VALUES(2, 'SOPHIA VASCONCELOS');

SELECT *FROM DEPENDENTES;

SELECT COD, CARGO FROM FUNCIONARIOS UNION SELECT 
COD, NOMEDEP FROM DEPENDENTES;


